name: Build KMP Desktop App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permission for Gradlew
        run: chmod +x gradlew

      - name: Build Windows Installer
        run: ./gradlew packageMsi

      - name: Upload Windows MSI Artifact
        uses: actions/upload-artifact@v3
        with:
          name: KMP-Windows-MSI
          path: build/compose/binaries/main/msi/

  build-macos:
    runs-on: macos-latest  # Use macOS runner for .dmg build
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK (JDK Eclipse 17)
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build macOS Installer (.dmg)
        run: ./gradlew packageReleaseDistributionForCurrentOS  # Build macOS packaging here

      - name: Upload macOS Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: KMP-macOS-DMG
          path: build/compose/binaries/main/dmg/  # Make sure this path points to the correct .dmg file
