name: Build KMP Desktop App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'coretto'
          java-version: '20'

      - name: Grant execute permission for gradlew
        run: git update-index --chmod=+x gradlew

      - name: Build Windows Executable (.msi)
        run: ./gradlew packageReleaseDistributionForCurrentOS

      - name: Upload Windows Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: KMP-Windows-MSI
          path: build/compose/binaries/main/msi/

  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'coretto'
          java-version: '20'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build macOS Installer (.dmg)
        run: ./gradlew packageReleaseDistributionForCurrentOS

      - name: Upload macOS Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: KMP-macOS-DMG
          path: build/compose/binaries/main/dmg/